[package]
name = "asn-wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
asn-logger = { git = "https://github.com/amberskynet/asn-logger.git", version = "3.1.0", features = [
] }
asn-gui-core = { path = "../asn-gui-core" }
asn-winit = { path = "../asn-winit" }
thiserror = "2.0"
anyhow = "1.0.98"
bytemuck = { version = "1.23", features = ["derive"] }
pollster = "0.4"
web-time = "1.0"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { version = "29.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "29.0", default-features = false, features = [
    "wgsl",
    "webgl",
    #    "dx12",
    #    "metal",
    #    "webgpu",
] }
