[package]
name = "ex_web_bus"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[build]
target = "wasm32-unknown-unknown"

[dependencies]
asn-core = { path = "../../modules/asn-core" }
asn-core-bus = { path = "../../modules/asn-core-bus" }
tokio-bus = { path = "../../modules/tokio-bus" }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
