[package]
name = "wgpu-map"
version = "0.1.0"
edition = "2024"

[dependencies]
asn-wgpu = { path = "../../../modules/asn-wgpu" }
bytemuck = { version = "1.23", features = ["derive"] }
rand = "0.10"
getrandom = { version = "0.4", features = ["wasm_js"] }
anyhow = "1.0.98"
asn-gui-core = { path = "../../../modules/asn-gui-core" }
asn-core = { path = "../../../modules/asn-core" }

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]